name: TeleportBow
version: '1.9'
main: org.teleport.tahoma.TeleportBow
api-version: '1.16'

commands:
  sbow:
    usage: /sbow [gui|remove]
    description: Give or manage the Teleport Bow
    aliases: [superbow, teleportbow]

permissions:
  teleportbow.use:
    description: Позволяет использовать Мега-Лук.
    default: true
  teleportbow.command:
    description: Доступ к команде /sbow.
    default: true